In [2]:
import numpy as np 
import pandas as pd

In [2]:
test = pd.read_csv('test_with_new_features.csv')
tst=pd.DataFrame(test)
test1 = pd.read_csv('xgboost2.csv')
tst1=pd.DataFrame(test1)

In [13]:
tst.head(7)

,trajectory_id,time_entry,time_exit,x_entry,y_entry,x_exit,y_exit,time_interval,distance,center,hash,same
0,traj_00032f51796fd5437b238e3a9823d13d_31_0,11:43:17,11:50:17,3.773413e+06,-1.909828e+07,3.773111e+06,-1.914508e+07,420,46799.053670,0,00032f51796fd5437b238e3a9823d13d_31,False
1,traj_00032f51796fd5437b238e3a9823d13d_31_2,12:21:37,12:21:37,3.773199e+06,-1.914354e+07,3.773199e+06,-1.914354e+07,0,0.000000,0,00032f51796fd5437b238e3a9823d13d_31,True
2,traj_00032f51796fd5437b238e3a9823d13d_31_3,12:34:27,13:14:11,3.763760e+06,-1.921342e+07,3.771757e+06,-1.911092e+07,2384,102806.725273,0,00032f51796fd5437b238e3a9823d13d_31,False
3,traj_00032f51796fd5437b238e3a9823d13d_31_4,13:25:33,13:43:13,3.773385e+06,-1.911344e+07,3.773131e+06,-1.914465e+07,1060,31209.541429,0,00032f51796fd5437b238e3a9823d13d_31,False
4,traj_00032f51796fd5437b238e3a9823d13d_31_5,15:03:32,15:10:32,3.773118e+06,-1.914490e+07,NaN,NaN,420,NaN,0,00032f51796fd5437b238e3a9823d13d_31,False
5,traj_000479418b5561ab694a2870cc04fd43_25_0,08:08:23,08:20:08,3.771380e+06,-1.933274e+07,3.769933e+06,-1.934095e+07,705,8339.038110,0,000479418b5561ab694a2870cc04fd43_25,False
6,traj_000479418b5561ab694a2870cc04fd43_25_6,12:08:23,12:13:24,3.771380e+06,-1.933274e+07,3.769983e+06,-1.934265e+07,301,10012.111189,0,000479418b5561ab694a2870cc04fd43_25,False

In [11]:
same=pd.DataFrame(pd.read_csv('test_without_sametime.csv'))

In [43]:
tst['hash']=same['hash']
tst['same']=same['sameTime']

In [44]:
tst=tst.drop_duplicates(subset='hash', keep='last', inplace=False)
tst.head(7)

,trajectory_id,time_entry,time_exit,x_entry,y_entry,x_exit,y_exit,time_interval,distance,center,hash,same
4,traj_00032f51796fd5437b238e3a9823d13d_31_5,15:03:32,15:10:32,3.773118e+06,-1.914490e+07,NaN,NaN,420,NaN,0,00032f51796fd5437b238e3a9823d13d_31,False
7,traj_000479418b5561ab694a2870cc04fd43_25_10,15:29:09,15:30:56,3.769978e+06,-1.934136e+07,NaN,NaN,107,NaN,0,000479418b5561ab694a2870cc04fd43_25,False
10,traj_000506a39775e5bca661ac80e3f466eb_29_5,15:26:08,15:26:08,3.757468e+06,-1.923860e+07,3.757468e+06,-1.923860e+07,0,0.0,1,000506a39775e5bca661ac80e3f466eb_29,True
13,traj_0005401ceddaf27a9b7f0d42ef1fbe95_1_4,15:35:18,15:42:05,3.760505e+06,-1.935500e+07,NaN,NaN,407,NaN,0,0005401ceddaf27a9b7f0d42ef1fbe95_1,False
17,traj_00063a4f6c12e1e4de7d876580620667_3_4,14:54:07,15:05:14,3.766319e+06,-1.917013e+07,NaN,NaN,667,NaN,0,00063a4f6c12e1e4de7d876580620667_3,False
23,traj_0006535be25bb52dd06983447880c964_5_12,15:22:06,15:22:06,3.776037e+06,-1.916993e+07,3.776037e+06,-1.916993e+07,0,0.0,0,0006535be25bb52dd06983447880c964_5,True
27,traj_0006f84bb33ec929d1cda7686f861d0a_31_3,15:00:12,15:00:12,3.760009e+06,-1.923361e+07,3.760009e+06,-1.923361e+07,0,0.0,1,0006f84bb33ec929d1cda7686f861d0a_31,True

In [45]:
tst.to_csv("middle1.csv",index=False,sep=',')
test = pd.read_csv('middle1.csv')
tst=pd.DataFrame(test)

In [ ]:
#tst.reindex(list,fill_value=0)
#list=()
#list=range(len(tst['trajectory_id']))

In [47]:
tst.head(7)

,trajectory_id,time_entry,time_exit,x_entry,y_entry,x_exit,y_exit,time_interval,distance,center,hash,same
0,traj_00032f51796fd5437b238e3a9823d13d_31_5,15:03:32,15:10:32,3.773118e+06,-1.914490e+07,NaN,NaN,420,NaN,0,00032f51796fd5437b238e3a9823d13d_31,False
1,traj_000479418b5561ab694a2870cc04fd43_25_10,15:29:09,15:30:56,3.769978e+06,-1.934136e+07,NaN,NaN,107,NaN,0,000479418b5561ab694a2870cc04fd43_25,False
2,traj_000506a39775e5bca661ac80e3f466eb_29_5,15:26:08,15:26:08,3.757468e+06,-1.923860e+07,3.757468e+06,-1.923860e+07,0,0.0,1,000506a39775e5bca661ac80e3f466eb_29,True
3,traj_0005401ceddaf27a9b7f0d42ef1fbe95_1_4,15:35:18,15:42:05,3.760505e+06,-1.935500e+07,NaN,NaN,407,NaN,0,0005401ceddaf27a9b7f0d42ef1fbe95_1,False
4,traj_00063a4f6c12e1e4de7d876580620667_3_4,14:54:07,15:05:14,3.766319e+06,-1.917013e+07,NaN,NaN,667,NaN,0,00063a4f6c12e1e4de7d876580620667_3,False
5,traj_0006535be25bb52dd06983447880c964_5_12,15:22:06,15:22:06,3.776037e+06,-1.916993e+07,3.776037e+06,-1.916993e+07,0,0.0,0,0006535be25bb52dd06983447880c964_5,True
6,traj_0006f84bb33ec929d1cda7686f861d0a_31_3,15:00:12,15:00:12,3.760009e+06,-1.923361e+07,3.760009e+06,-1.923361e+07,0,0.0,1,0006f84bb33ec929d1cda7686f861d0a_31,True

In [48]:
tst['c']=tst1['target']

In [50]:
tst.head(17)

,trajectory_id,time_entry,time_exit,x_entry,y_entry,x_exit,y_exit,time_interval,distance,center,hash,same,c
0,traj_00032f51796fd5437b238e3a9823d13d_31_5,15:03:32,15:10:32,3.773118e+06,-1.914490e+07,NaN,NaN,420,NaN,0,00032f51796fd5437b238e3a9823d13d_31,False,0
1,traj_000479418b5561ab694a2870cc04fd43_25_10,15:29:09,15:30:56,3.769978e+06,-1.934136e+07,NaN,NaN,107,NaN,0,000479418b5561ab694a2870cc04fd43_25,False,0
2,traj_000506a39775e5bca661ac80e3f466eb_29_5,15:26:08,15:26:08,3.757468e+06,-1.923860e+07,3.757468e+06,-1.923860e+07,0,0.0,1,000506a39775e5bca661ac80e3f466eb_29,True,1
3,traj_0005401ceddaf27a9b7f0d42ef1fbe95_1_4,15:35:18,15:42:05,3.760505e+06,-1.935500e+07,NaN,NaN,407,NaN,0,0005401ceddaf27a9b7f0d42ef1fbe95_1,False,0
4,traj_00063a4f6c12e1e4de7d876580620667_3_4,14:54:07,15:05:14,3.766319e+06,-1.917013e+07,NaN,NaN,667,NaN,0,00063a4f6c12e1e4de7d876580620667_3,False,0
5,traj_0006535be25bb52dd06983447880c964_5_12,15:22:06,15:22:06,3.776037e+06,-1.916993e+07,3.776037e+06,-1.916993e+07,0,0.0,0,0006535be25bb52dd06983447880c964_5,True,0
6,traj_0006f84bb33ec929d1cda7686f861d0a_31_3,15:00:12,15:00:12,3.760009e+06,-1.923361e+07,3.760009e+06,-1.923361e+07,0,0.0,1,0006f84bb33ec929d1cda7686f861d0a_31,True,1
7,traj_00093ae562586aed0e053b8431e8ace4_23_10,15:53:09,15:53:09,3.756665e+06,-1.914692e+07,3.756665e+06,-1.914692e+07,0,0.0,0,00093ae562586aed0e053b8431e8ace4_23,True,0
8,traj_000c739e444a70e1804d757a0580caaa_31_3,15:41:31,15:41:31,3.768082e+06,-1.922134e+07,3.768082e+06,-1.922134e+07,0,0.0,1,000c739e444a70e1804d757a0580caaa_31,True,1
9,traj_000d479078af08618bddc7f09082b8c3_11_6,14:58:06,15:03:40,3.766505e+06,-1.920176e+07,NaN,NaN,334,NaN,0,000d479078af08618bddc7f09082b8c3_11,False,0
10,traj_000d6fba12a7d06defe90e3c9162c11e_29_11,15:40:02,15:40:02,3.758716e+06,-1.922511e+07,3.758716e+06,-1.922511e+07,0,0.0,1,000d6fba12a7d06defe90e3c9162c11e_29,True,1
11,traj_000efd6f95db39d6ba35027f02b5628f_9_20,14:52:00,15:22:47,3.757810e+06,-1.923589e+07,NaN,NaN,1847,NaN,0,000efd6f95db39d6ba35027f02b5628f_9,False,1
12,traj_000feace3a33be9245e2783cdff467a8_15_12,15:21:42,15:38:48,3.772423e+06,-1.916282e+07,NaN,NaN,1026,NaN,0,000feace3a33be9245e2783cdff467a8_15,False,0
13,traj_0011b48d0cf4f962833edd701afaf419_3_7,15:26:00,15:28:31,3.760741e+06,-1.906436e+07,NaN,NaN,151,NaN,0,0011b48d0cf4f962833edd701afaf419_3,False,0
14,traj_001484cf0f956c316070be4b4c6352ff_29_7,13:38:07,15:00:22,3.757791e+06,-1.919034e+07,NaN,NaN,4935,NaN,0,001484cf0f956c316070be4b4c6352ff_29,False,0
15,traj_001d29060cfe35996cfeb141210ecbeb_9_2,15:21:39,15:25:36,3.754465e+06,-1.924045e+07,NaN,NaN,237,NaN,0,001d29060cfe35996cfeb141210ecbeb_9,False,1
16,traj_001dff40eab7eea1c10d0fadcea0c779_9_7,14:36:47,15:09:41,3.753184e+06,-1.910524e+07,NaN,NaN,1974,NaN,0,001dff40eab7eea1c10d0fadcea0c779_9,False,0

In [51]:
e=[]
for row in tst.itertuples(index=True, name='Pandas'):
    if getattr(row, "same"):
        e.append(getattr(row, "center"))
    else:
        e.append(getattr(row, "c"))
e

[0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 ...]

In [54]:
tst['center']=e

In [53]:
tst.head(7)

,trajectory_id,time_entry,time_exit,x_entry,y_entry,x_exit,y_exit,time_interval,distance,center,hash,same,c
0,traj_00032f51796fd5437b238e3a9823d13d_31_5,15:03:32,15:10:32,3.773118e+06,-1.914490e+07,NaN,NaN,420,NaN,0,00032f51796fd5437b238e3a9823d13d_31,False,0
1,traj_000479418b5561ab694a2870cc04fd43_25_10,15:29:09,15:30:56,3.769978e+06,-1.934136e+07,NaN,NaN,107,NaN,0,000479418b5561ab694a2870cc04fd43_25,False,0
2,traj_000506a39775e5bca661ac80e3f466eb_29_5,15:26:08,15:26:08,3.757468e+06,-1.923860e+07,3.757468e+06,-1.923860e+07,0,0.0,1,000506a39775e5bca661ac80e3f466eb_29,True,1
3,traj_0005401ceddaf27a9b7f0d42ef1fbe95_1_4,15:35:18,15:42:05,3.760505e+06,-1.935500e+07,NaN,NaN,407,NaN,0,0005401ceddaf27a9b7f0d42ef1fbe95_1,False,0
4,traj_00063a4f6c12e1e4de7d876580620667_3_4,14:54:07,15:05:14,3.766319e+06,-1.917013e+07,NaN,NaN,667,NaN,0,00063a4f6c12e1e4de7d876580620667_3,False,0
5,traj_0006535be25bb52dd06983447880c964_5_12,15:22:06,15:22:06,3.776037e+06,-1.916993e+07,3.776037e+06,-1.916993e+07,0,0.0,0,0006535be25bb52dd06983447880c964_5,True,0
6,traj_0006f84bb33ec929d1cda7686f861d0a_31_3,15:00:12,15:00:12,3.760009e+06,-1.923361e+07,3.760009e+06,-1.923361e+07,0,0.0,1,0006f84bb33ec929d1cda7686f861d0a_31,True,1

In [66]:
tst.head(7)

,trajectory_id,time_entry,time_exit,x_entry,y_entry,x_exit,y_exit,time_interval,distance,center,hash,same,c
0,traj_00032f51796fd5437b238e3a9823d13d_31_5,15:03:32,15:10:32,3.773118e+06,-1.914490e+07,NaN,NaN,420,NaN,0,00032f51796fd5437b238e3a9823d13d_31,False,0
1,traj_000479418b5561ab694a2870cc04fd43_25_10,15:29:09,15:30:56,3.769978e+06,-1.934136e+07,NaN,NaN,107,NaN,0,000479418b5561ab694a2870cc04fd43_25,False,0
2,traj_000506a39775e5bca661ac80e3f466eb_29_5,15:26:08,15:26:08,3.757468e+06,-1.923860e+07,3.757468e+06,-1.923860e+07,0,0.0,1,000506a39775e5bca661ac80e3f466eb_29,True,1
3,traj_0005401ceddaf27a9b7f0d42ef1fbe95_1_4,15:35:18,15:42:05,3.760505e+06,-1.935500e+07,NaN,NaN,407,NaN,1,0005401ceddaf27a9b7f0d42ef1fbe95_1,False,1
4,traj_00063a4f6c12e1e4de7d876580620667_3_4,14:54:07,15:05:14,3.766319e+06,-1.917013e+07,NaN,NaN,667,NaN,0,00063a4f6c12e1e4de7d876580620667_3,False,0
5,traj_0006535be25bb52dd06983447880c964_5_12,15:22:06,15:22:06,3.776037e+06,-1.916993e+07,3.776037e+06,-1.916993e+07,0,0.0,0,0006535be25bb52dd06983447880c964_5,True,0
6,traj_0006f84bb33ec929d1cda7686f861d0a_31_3,15:00:12,15:00:12,3.760009e+06,-1.923361e+07,3.760009e+06,-1.923361e+07,0,0.0,1,0006f84bb33ec929d1cda7686f861d0a_31,True,0

In [55]:
tst1['target']=e

In [57]:
tst1.head(17)

                                             id  target
0    traj_00032f51796fd5437b238e3a9823d13d_31_5       0
1   traj_000479418b5561ab694a2870cc04fd43_25_10       0
2    traj_000506a39775e5bca661ac80e3f466eb_29_5       1
3     traj_0005401ceddaf27a9b7f0d42ef1fbe95_1_4       0
4     traj_00063a4f6c12e1e4de7d876580620667_3_4       0
5    traj_0006535be25bb52dd06983447880c964_5_12       0
6    traj_0006f84bb33ec929d1cda7686f861d0a_31_3       1
7   traj_00093ae562586aed0e053b8431e8ace4_23_10       0
8    traj_000c739e444a70e1804d757a0580caaa_31_3       1
9    traj_000d479078af08618bddc7f09082b8c3_11_6       0
10  traj_000d6fba12a7d06defe90e3c9162c11e_29_11       1
11   traj_000efd6f95db39d6ba35027f02b5628f_9_20       1
12  traj_000feace3a33be9245e2783cdff467a8_15_12       0
13    traj_0011b48d0cf4f962833edd701afaf419_3_7       0
14   traj_001484cf0f956c316070be4b4c6352ff_29_7       0
15    traj_001d29060cfe35996cfeb141210ecbeb_9_2       1
16    traj_001dff40eab7eea1c10d0fadcea0c779_9_7       0

In [58]:
tst1.head(17)

                                             id  target
0    traj_00032f51796fd5437b238e3a9823d13d_31_5       0
1   traj_000479418b5561ab694a2870cc04fd43_25_10       0
2    traj_000506a39775e5bca661ac80e3f466eb_29_5       1
3     traj_0005401ceddaf27a9b7f0d42ef1fbe95_1_4       0
4     traj_00063a4f6c12e1e4de7d876580620667_3_4       0
5    traj_0006535be25bb52dd06983447880c964_5_12       0
6    traj_0006f84bb33ec929d1cda7686f861d0a_31_3       1
7   traj_00093ae562586aed0e053b8431e8ace4_23_10       0
8    traj_000c739e444a70e1804d757a0580caaa_31_3       1
9    traj_000d479078af08618bddc7f09082b8c3_11_6       0
10  traj_000d6fba12a7d06defe90e3c9162c11e_29_11       1
11   traj_000efd6f95db39d6ba35027f02b5628f_9_20       1
12  traj_000feace3a33be9245e2783cdff467a8_15_12       0
13    traj_0011b48d0cf4f962833edd701afaf419_3_7       0
14   traj_001484cf0f956c316070be4b4c6352ff_29_7       0
15    traj_001d29060cfe35996cfeb141210ecbeb_9_2       1
16    traj_001dff40eab7eea1c10d0fadcea0c779_9_7       0

In [59]:
tst1.to_csv("2_change_xgboost.csv",index=False,sep=',')

In [ ]:
#判断center那一行，大等于0.5的就是1,小于0.5的就是0

In [3]:
test = pd.read_csv('test_with_new_features.csv')
tst=pd.DataFrame(test)
test1 = pd.read_csv('xgboost3.csv')
tst1=pd.DataFrame(test1)

In [4]:
#判断center那一行，大等于0.5的就是1,小于0.5的就是0
e1=[]
for row in tst1.itertuples(index=True, name='Pandas'):
    if getattr(row, "target")>= 0.5:
        e1.append(1)
    else:
        e1.append(0)
e1

[0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 ...]

In [6]:
tst1['target']=e1

In [7]:
tst1.head(7)

                                            id  target
0   traj_00032f51796fd5437b238e3a9823d13d_31_5       0
1  traj_000479418b5561ab694a2870cc04fd43_25_10       0
2   traj_000506a39775e5bca661ac80e3f466eb_29_5       1
3    traj_0005401ceddaf27a9b7f0d42ef1fbe95_1_4       0
4    traj_00063a4f6c12e1e4de7d876580620667_3_4       0
5   traj_0006535be25bb52dd06983447880c964_5_12       0
6   traj_0006f84bb33ec929d1cda7686f861d0a_31_3       1

In [8]:
tst1.to_csv("submission2.csv",index=False,sep=',')