In [2]:
#train_without_same合并训练集和测试集
import numpy as np 
import pandas as pd

In [19]:
tra = pd.DataFrame(pd.read_csv('train_with_new_features.csv'))
tst = pd.DataFrame(pd.read_csv('test_with_new_features.csv'))

In [7]:
tra.head(7)

,trajectory_id,time_entry,time_exit,x_entry,y_entry,x_exit,y_exit,time_interval,distance,center,sameTime
0,traj_0000a8602cf2def930488dee7cdad104_1_0,07:04:31,07:08:32,3.751014e+06,-1.909398e+07,3.750326e+06,-1.913634e+07,241,42364.863118,0,False
1,traj_0000a8602cf2def930488dee7cdad104_1_1,07:20:34,07:25:42,3.743937e+06,-1.932247e+07,3.744975e+06,-1.931966e+07,308,2989.643628,0,False
2,traj_0000a8602cf2def930488dee7cdad104_1_2,07:53:32,08:03:25,3.744868e+06,-1.929356e+07,3.744816e+06,-1.929284e+07,593,725.658561,0,False
3,traj_0000a8602cf2def930488dee7cdad104_1_3,08:17:50,08:37:23,3.744880e+06,-1.929229e+07,3.744809e+06,-1.929049e+07,1173,1804.576849,0,False
4,traj_0000a8602cf2def930488dee7cdad104_1_4,14:38:09,14:38:09,3.744909e+06,-1.928558e+07,3.744909e+06,-1.928558e+07,0,0.000000,0,True
5,traj_0000a8602cf2def930488dee7cdad104_1_5,15:02:31,15:18:33,3.744945e+06,-1.928183e+07,3.744785e+06,-1.928148e+07,962,389.513093,0,False
6,traj_0000cf177130469eeac79f67b6bcf3df_9_0,14:29:23,14:29:23,3.749450e+06,-1.926506e+07,3.749450e+06,-1.926506e+07,0,0.000000,0,True

In [6]:
sameTime=(tra['time_entry'] == tra['time_exit'])
tra['sameTime']=sameTime

In [9]:
#tra=tra.drop(['hash','center'], axis=1)#0删除行，1删除列
tra1=tra[ tra['sameTime'] == False ]

In [15]:
tra1.head(7)

,trajectory_id,time_entry,time_exit,x_entry,y_entry,x_exit,y_exit,time_interval,distance,center
0,traj_0000a8602cf2def930488dee7cdad104_1_0,07:04:31,07:08:32,3.751014e+06,-1.909398e+07,3.750326e+06,-1.913634e+07,241,42364.863118,NaN
1,traj_0000a8602cf2def930488dee7cdad104_1_1,07:20:34,07:25:42,3.743937e+06,-1.932247e+07,3.744975e+06,-1.931966e+07,308,2989.643628,NaN
2,traj_0000a8602cf2def930488dee7cdad104_1_2,07:53:32,08:03:25,3.744868e+06,-1.929356e+07,3.744816e+06,-1.929284e+07,593,725.658561,NaN
3,traj_0000a8602cf2def930488dee7cdad104_1_3,08:17:50,08:37:23,3.744880e+06,-1.929229e+07,3.744809e+06,-1.929049e+07,1173,1804.576849,NaN
5,traj_0000a8602cf2def930488dee7cdad104_1_5,15:02:31,15:18:33,3.744945e+06,-1.928183e+07,3.744785e+06,-1.928148e+07,962,389.513093,NaN
9,traj_0000cf177130469eeac79f67b6bcf3df_9_3,15:00:32,15:29:48,3.749088e+06,-1.926605e+07,3.749610e+06,-1.926594e+07,1756,534.474570,NaN
10,traj_0001f97b99a80f18f62e2d44e54ef33d_3_0,11:37:06,11:52:08,3.771461e+06,-1.910413e+07,3.757004e+06,-1.929698e+07,902,193384.920615,NaN

In [11]:
tra1=tra1.drop(columns=['center','sameTime'], axis=1)

In [14]:
tra1['center']=np.nan

In [17]:
tra1.to_csv("tra1.csv",index=False,sep=',')

In [51]:
tst1.head(17)

,trajectory_id,time_entry,time_exit,x_entry,y_entry,x_exit,y_exit,time_interval,distance,center,e
0,traj_00032f51796fd5437b238e3a9823d13d_31_0,11:43:17,11:50:17,3.773413e+06,-1.909828e+07,3.773111e+06,-1.914508e+07,420,46799.053670,0,False
2,traj_00032f51796fd5437b238e3a9823d13d_31_3,12:34:27,13:14:11,3.763760e+06,-1.921342e+07,3.771757e+06,-1.911092e+07,2384,102806.725273,0,False
3,traj_00032f51796fd5437b238e3a9823d13d_31_4,13:25:33,13:43:13,3.773385e+06,-1.911344e+07,3.773131e+06,-1.914465e+07,1060,31209.541429,0,False
4,traj_00032f51796fd5437b238e3a9823d13d_31_5,15:03:32,15:10:32,3.773118e+06,-1.914490e+07,NaN,NaN,420,NaN,0,True
5,traj_000479418b5561ab694a2870cc04fd43_25_0,08:08:23,08:20:08,3.771380e+06,-1.933274e+07,3.769933e+06,-1.934095e+07,705,8339.038110,0,False
6,traj_000479418b5561ab694a2870cc04fd43_25_6,12:08:23,12:13:24,3.771380e+06,-1.933274e+07,3.769983e+06,-1.934265e+07,301,10012.111189,0,False
7,traj_000479418b5561ab694a2870cc04fd43_25_10,15:29:09,15:30:56,3.769978e+06,-1.934136e+07,NaN,NaN,107,NaN,0,True
8,traj_000506a39775e5bca661ac80e3f466eb_29_1,08:45:05,08:50:33,3.760880e+06,-1.910042e+07,3.759312e+06,-1.908280e+07,328,17692.697690,0,False
13,traj_0005401ceddaf27a9b7f0d42ef1fbe95_1_4,15:35:18,15:42:05,3.760505e+06,-1.935500e+07,NaN,NaN,407,NaN,0,True
14,traj_00063a4f6c12e1e4de7d876580620667_3_1,08:48:38,09:33:56,3.747364e+06,-1.927846e+07,3.774308e+06,-1.911005e+07,2718,170556.085938,0,False
15,traj_00063a4f6c12e1e4de7d876580620667_3_2,12:53:38,12:58:19,3.776268e+06,-1.918284e+07,3.776260e+06,-1.918272e+07,281,124.457978,0,False
16,traj_00063a4f6c12e1e4de7d876580620667_3_3,14:18:20,14:35:02,3.776264e+06,-1.918289e+07,3.766296e+06,-1.917029e+07,1002,16067.466470,0,False
17,traj_00063a4f6c12e1e4de7d876580620667_3_4,14:54:07,15:05:14,3.766319e+06,-1.917013e+07,NaN,NaN,667,NaN,0,True
24,traj_0006f84bb33ec929d1cda7686f861d0a_31_0,12:01:39,12:09:32,3.761176e+06,-1.925510e+07,3.761184e+06,-1.925448e+07,473,616.716207,1,False
32,traj_000c739e444a70e1804d757a0580caaa_31_0,11:21:19,11:42:15,3.772885e+06,-1.908844e+07,3.767987e+06,-1.922306e+07,1256,134707.412009,1,False
35,traj_000d479078af08618bddc7f09082b8c3_11_0,13:42:32,13:55:10,3.744857e+06,-1.929530e+07,3.744840e+06,-1.929690e+07,758,1597.698288,0,False
38,traj_000d479078af08618bddc7f09082b8c3_11_4,14:35:59,14:57:06,3.744812e+06,-1.932195e+07,3.767684e+06,-1.920421e+07,1267,119940.674425,0,False

In [45]:
tst = pd.DataFrame(pd.read_csv('test_with_new_features.csv'))

In [47]:
tst1=tst[ tst['time_interval'] != 0 ]

In [49]:
e=[]
e=pd.isnull(tst['x_exit'])

In [50]:
tst1['e']=e

/Users/YAO/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [52]:
tst1=tst1[ tst1['e'] == False ]

In [56]:
tst1.head(17)

,trajectory_id,time_entry,time_exit,x_entry,y_entry,x_exit,y_exit,time_interval,distance,center
0,traj_00032f51796fd5437b238e3a9823d13d_31_0,11:43:17,11:50:17,3.773413e+06,-1.909828e+07,3.773111e+06,-1.914508e+07,420,46799.053670,0
2,traj_00032f51796fd5437b238e3a9823d13d_31_3,12:34:27,13:14:11,3.763760e+06,-1.921342e+07,3.771757e+06,-1.911092e+07,2384,102806.725273,0
3,traj_00032f51796fd5437b238e3a9823d13d_31_4,13:25:33,13:43:13,3.773385e+06,-1.911344e+07,3.773131e+06,-1.914465e+07,1060,31209.541429,0
5,traj_000479418b5561ab694a2870cc04fd43_25_0,08:08:23,08:20:08,3.771380e+06,-1.933274e+07,3.769933e+06,-1.934095e+07,705,8339.038110,0
6,traj_000479418b5561ab694a2870cc04fd43_25_6,12:08:23,12:13:24,3.771380e+06,-1.933274e+07,3.769983e+06,-1.934265e+07,301,10012.111189,0
8,traj_000506a39775e5bca661ac80e3f466eb_29_1,08:45:05,08:50:33,3.760880e+06,-1.910042e+07,3.759312e+06,-1.908280e+07,328,17692.697690,0
14,traj_00063a4f6c12e1e4de7d876580620667_3_1,08:48:38,09:33:56,3.747364e+06,-1.927846e+07,3.774308e+06,-1.911005e+07,2718,170556.085938,0
15,traj_00063a4f6c12e1e4de7d876580620667_3_2,12:53:38,12:58:19,3.776268e+06,-1.918284e+07,3.776260e+06,-1.918272e+07,281,124.457978,0
16,traj_00063a4f6c12e1e4de7d876580620667_3_3,14:18:20,14:35:02,3.776264e+06,-1.918289e+07,3.766296e+06,-1.917029e+07,1002,16067.466470,0
24,traj_0006f84bb33ec929d1cda7686f861d0a_31_0,12:01:39,12:09:32,3.761176e+06,-1.925510e+07,3.761184e+06,-1.925448e+07,473,616.716207,1
32,traj_000c739e444a70e1804d757a0580caaa_31_0,11:21:19,11:42:15,3.772885e+06,-1.908844e+07,3.767987e+06,-1.922306e+07,1256,134707.412009,1
35,traj_000d479078af08618bddc7f09082b8c3_11_0,13:42:32,13:55:10,3.744857e+06,-1.929530e+07,3.744840e+06,-1.929690e+07,758,1597.698288,0
38,traj_000d479078af08618bddc7f09082b8c3_11_4,14:35:59,14:57:06,3.744812e+06,-1.932195e+07,3.767684e+06,-1.920421e+07,1267,119940.674425,0
40,traj_000d6fba12a7d06defe90e3c9162c11e_29_0,08:39:01,08:56:56,3.758368e+06,-1.935011e+07,3.759230e+06,-1.922743e+07,1075,122681.469635,1
41,traj_000d6fba12a7d06defe90e3c9162c11e_29_3,12:39:43,12:54:00,3.758444e+06,-1.935123e+07,3.758244e+06,-1.922768e+07,857,123552.844336,1
42,traj_000d6fba12a7d06defe90e3c9162c11e_29_5,12:54:14,12:56:56,3.758107e+06,-1.922749e+07,3.759230e+06,-1.922743e+07,162,1124.651730,1
46,traj_000efd6f95db39d6ba35027f02b5628f_9_0,12:06:10,12:51:09,3.742579e+06,-1.927611e+07,3.745063e+06,-1.930620e+07,2699,30192.329930,0

In [54]:
tst1=tst1.drop(columns=['e'], axis=1)

In [58]:
tra = pd.DataFrame(pd.read_csv('tra1.csv'))

In [60]:
tra['ee']=((tra['x_exit']>=3750901.5068) & (tra['x_exit']<=3770901.5068)) & ((tra['y_exit']>=-19268905.6133) & (tra['y_exit']<=-19208905.6133))

In [63]:
e=[]
for row in tra.itertuples(index=True, name='Pandas'):
    if getattr(row, "ee"):
        e.append(1)
    else:
        e.append(0)
tra['center']=e

In [65]:
tra=tra.drop(columns=['ee'], axis=1)

In [67]:
tra.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381185 entries, 0 to 381184
Data columns (total 10 columns):
trajectory_id    381185 non-null object
time_entry       381185 non-null object
time_exit        381185 non-null object
x_entry          381185 non-null float64
y_entry          381185 non-null float64
x_exit           381185 non-null float64
y_exit           381185 non-null float64
time_interval    381185 non-null int64
distance         381185 non-null float64
center           381185 non-null int64
dtypes: float64(5), int64(2), object(3)
memory usage: 29.1+ MB

In [68]:
tra.to_csv("tra1.csv",index=False,sep=',')